# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - OrdinarioBalam

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ordcontbalam.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2fd48b13f87c4ffbac79e13f51a080a5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f545963db394d73881ca4202b459e58 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ordcontbalam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2fd48b13f87c4ffbac79e13f51a080a5 }}/ordinarioback:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'OrdinarioBalam'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7064e11e7cef466c99641f607c99a969 }}
        images: 'ordcontbalam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2fd48b13f87c4ffbac79e13f51a080a5 }}/ordinarioback:${{ github.sha }}'